
```{r}
install.packages(c('survival', 'survminer', 'dplyr', 'summarytools'))
```

```{r}
library('survival')
library('survminer')
library('dplyr')
library('summarytools')
```


```{r}
data <- read.delim('ThirdBirth.txt', sep = '')
data <- tibble::rowid_to_column(data, "ID")
data$spacing_months = data$spacing / 30.5
data$time_months = data$time / 30.5
data$sibs = factor(data$sibs)
data$sibs = relevel(data$sibs, ref = 2)
col_order <- c('ID', 'age', 'spacing', 'spacing_months', 'sibs', 'time', 'time_months', 'status')
data <- data[, col_order]
head(data)
```

```{r}
str(data)
```

```{r}
summary(data[c('age', 'spacing', 'spacing_months', 'time', 'time_months')])
```

# Descriptive statistics.

```{r}
mean(data$age)
sd(data$age)
var(data$age)
```

```{r}
mean(data$spacing_months)
sd(data$spacing_months)
var(data$spacing_months)
```

```{r}
mean(data$time_months)
sd(data$time_months)
var(data$time_months)
```

```{r}
data_birth <- data[which(data$status == 1),]
str(data_birth)
```

```{r}
summary(data_birth$time_months)
```

```{r}
mean(data_birth$time_months)
sd(data_birth$time_months)
var(data_birth$time_months)
```

```{r}
freq(data$sibs)
```

```{r}
freq(data$status)
```

# Kaplan-Meier and Log-rank for comparisons of survival probabilities.

```{r}
fit <- survfit(Surv(time_months, status) ~ 1, data = data)
print(fit)
```

```{r}
plot(fit, lwd = 1, xlab = 'Time in months', ylab = 'Survival probability')
```

```{r}
ggsurvplot(fit, data = data, color = '#2E9FDF',
           conf.int = TRUE,
           conf.int.style = "step",
           risk.table = "percentage",
           xlab = 'Time in months',
           break.time.by = 12,
           ggtheme = theme_minimal())
```


```{r}
fit_sibs <- survfit(Surv(time_months, status) ~ sibs, data = data)
print(fit_sibs)
```

```{r}
plot(fit_sibs, col = c('blue', 'deeppink', 'forestgreen', 'orange'), lwd = 2, xlab = 'Time in months', ylab = 'Survival probability')
legend('topright', lty = 1, col = c('blue', 'deeppink', 'forestgreen', 'orange'), lwd = 2, legend = c('Boy, boy', 'Girl, girl', 'Boy, girl', 'Girl, boy'))
```


```{r}
ggsurvplot(fit_sibs, 
          data = data,
          pval = TRUE,
          conf.int = TRUE,
          conf.int.style = "step",
          surv.plot.height = 1,
          risk.table = "percentage",
          risk.table.col = "strata", 
          tables.height = 0.35,
          legend.labs=c('Boy, boy', 'Girl, girl', 'Boy, girl', 'Girl, boy'),
          linetype = "strata", 
          surv.median.line = "hv",
          xlab = "Time in months",
          break.time.by = 12,
          ggtheme = theme_bw())
```


```{r}
surv_diff <- survdiff(Surv(time_months, status) ~ sibs, data = data)
surv_diff
```


# Multivariate Cox regression model

```{r}
fit <- coxph(Surv(time, status) ~ age + spacing + sibs, data = data)
summary(fit)
```

# Model evaluation.

## Testing proportionality of hazards.

```{r}
test.ph <- cox.zph(fit)
test.ph
```

```{r}
ggcoxzph(test.ph)
```

## Testing for influential observations.

```{r}
ggcoxdiagnostics(fit, type = 'deviance', 
                 linear.predictions = FALSE, ggtheme = theme_bw())
```

```{r}
ggcoxdiagnostics(fit, type = 'dfbetas', 
                 linear.predictions = FALSE, ggtheme = theme_bw())
```


## Testing for linearity.

```{r}
data$residual <- residuals(fit, type = 'martingale')
```

```{r}
par(mfrow = c(1, 3), mar = c(4.2, 2, 2, 2))
with(data, {

  plot(age, residual)
  lines(lowess(age, residual), lwd = 2)

  plot(spacing, residual)
  lines(lowess(spacing, residual), lwd = 2)

  plot(residual ~ sibs, caption = 'Gender')

})
```


# Data segmentation.

```{r}
new_data <- read.delim('ThirdBirthTest.txt', sep = '')
head(new_data)
```

```{r}
new_data <- tibble::rowid_to_column(new_data, "ID")
new_data <- select(new_data, -time, -status)
new_data$spacing_months = new_data$spacing / 30.5
col_order <- c('ID', 'age', 'spacing', 'spacing_months', 'sibs')
new_data <- new_data[, col_order]
head(new_data)
```

```{r}
new_data <- mutate(new_data, sibs = relevel(factor(sibs), ref = 2))
```

```{r}
new_data_segmented <-
  new_data %>%
  mutate(risk_score = predict(fit, newdata = new_data, type = "lp"))
head(new_data_segmented)
```

```{r}
new_data_segmented %>%
  arrange(desc(risk_score)) %>%
  top_n(80)
```
















